eureka:
  client:
    register-with-eureka: true # This is a eureka server client
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/ # eureka server target
  instance:
    hostname: localhost
